config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :images

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_attached_file :picture, styles: { medium: "800x800>", thumb: "250x250>" }, default_url: "/images/default.jpg"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  validates :description, presence:true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_devise_params, if: :devise_controller?

  def configure_devise_params
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @images = Image.paginate(:page => params[:page], :per_page => 9)
                    .order(id: :desc)
                    .where user_id: current_user.id
    end


  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.where user_id: current_user.id
  end
  def new
    @image = Image.new
  end
  def create
    @image = current_user.images.new image_params

    if @image.save
      return redirect_to images_path
    end

    render :new
  end
  def show
  end
  def edit
  end
  def update
    @image.update image_params
    redirect_to images_path
  end
  def destroy
    @image.destroy

    redirect_to images_path
  end

  private
  def image_params
    params.require(:image).permit :description, :picture
  end
  def set_image
    @image = Image.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>

  <div class="row">
    <div class="col-4">

    </div>
    <div class="col-8">
      <h1><%= current_user.name %></h1>
      <div>
        <ul class="nav">
          <li class="margin-righy">
            <p><strong><%= @images.count %></strong> Publicaciones</p>
          </li>
          <li class="margin-righy">
            <p><strong>300</strong> Seguidores</p>
          </li>
          <li class="margin-righy">
            <p><strong>250</strong> Seguidos</p>
          </li>


        </ul>
      </div>
    </div>
  </div>
    <div class="row" id="images">
      <%= render @images %>
    </div>
  <%= will_paginate @images %>

<% else %>
  <h1>Ruby on Rails</h1>
<% end %>

app/views/home/index.js.erb
$('#images').append('<%= j render @images %>')

<% if @images.next_page %>
$('.pagination').replaceWith('<%= j will_paginate @images %>')
<% else %>
  $('.pagination').remove();
<% end %>

app/views/images/_form.html.erb
<div class="form-group">
<%= form_for @image, html: { multipart: true }, builder: CustomFormBuilder do |f|  %>
  <%= f.form_error %>


  <%=f.label :description %>
  <%=f.text_field :description, class: 'form-control' %>
    <%= f.field_error :description %>
    <br>
  <%=f.label :imagen %><br>
  <%= f.file_field :picture %>
  <%= f.submit 'Enviar', class: 'btn btn-primary mt-3' %>
<%end  %>
</div>

app/views/images/_image.html.erb
<div class="col-4 mt-3">
<figure class="figure">
  <%= image_tag image.picture.url(:medium), class: 'figure-img img-fluid rounded' %>
  <figcaption class="figure-caption"><%= image.description %>
    <%= link_to t('.edit_link'), edit_image_path(image) %>
    <%= link_to t('.remove_link'), image, method: :delete,data:{confirm: 'sure?'} %>
  </figcaption>
</figure>
</div>

app/views/images/edit.html.erb
<div class="container">
  <h1>Editar Formulario</h1>
  <%= render 'form' %>
</div>

app/views/images/index.html.erb
<div class="container">
  <div class="row">
    <%= render @images %>
  </div>
</div>

app/views/images/new.html.erb
<div class="container">
  <h1>Crear</h1>
  <%= render 'form' %>
</div>

app/views/images/show.html.erb
<%= image_tag @image.picture.url, class: 'figure-img img-fluid rounded' %>
<%= @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Community</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul class="nav justify-content-end">
    <%- if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <%else %>
      <li class="nav-item">
        <%= link_to 'Iniciar', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Registrarme', new_user_registration_path, class: 'nav-link' %>
      </li>
    <%end %>
  </ul>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>